prefix=/usr
datadir=$(prefix)/share
sysconfdir=/etc
unitdir=$(prefix)/lib/systemd/system
pkgdatadir=$(datadir)/osc-plugin-factory
oscplugindir=$(prefix)/lib/osc-plugins
apachevhostsdir=$(sysconfdir)/apache2/vhosts.d
