#!/usr/bin/env sh
/usr/share/openSUSE-release-tools/verify-repo-built-successful.py -A $API_URL -p $1 -r standard
/usr/bin/osrt-pkglistgen -A $API_URL --debug update_and_solve -p $1 -s target --force
