{
 "title": "OSRT: Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Devel Projects",
   "type": "graph",
   "description": "The number of devel projects utilized.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dashboard_devel_projects",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repo Checker Issues",
   "type": "graph",
   "description": "The number of issues detect in main project by repo-checker by type plus line count.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dashboard_repo_checker",
     "select": [
      [
       { "params": [ "conflict_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "conflict" ], "type": "alias" }
      ],
      [
       { "params": [ "install_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "install" ], "type": "alias" }
      ],
      [
       { "params": [ "line_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "line" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repo Checker Whitelist",
   "type": "graph",
   "description": "The number of binaries whitelisted from repo-checker during staging process.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dashboard_config",
     "select": [
      [
       { "params": [ "repo_checker-binary-whitelist" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "all" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "repo_checker-binary-whitelist-i586"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "i586" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "repo_checker-binary-whitelist-x86_64"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "x86_64" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weekly Releases",
   "type": "graph",
   "description": "The number of releases made during a week.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "dashboard_version_snapshot",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weekly Revisions",
   "type": "graph",
   "description": "The number of revisions to dashboard container made during a week.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "dashboard_revision",
     "select": [
      [
       { "params": [ "revision" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}