{
 "title": "OSRT: OpenQA",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Queue: State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Scheduled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs",
     "select": [
      [
       { "params": [ "scheduled" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queue: Groups",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs_by_group",
     "query": "SELECT mean(\"running\") + mean(\"scheduled\") + mean(\"blocked\") FROM \"openqa_jobs_by_group\" WHERE $timeFilter GROUP BY time($__interval), \"group\" fill(0)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queue: Architecture",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_arch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs_by_arch",
     "query": "SELECT mean(\"running\") + mean(\"scheduled\") + mean(\"blocked\") FROM \"openqa_jobs_by_arch\" WHERE $timeFilter GROUP BY time($__interval), \"arch\" fill(0)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running by Worker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_worker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs_by_worker",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}