{
 "title": "OSRT: Release",
 "description": "Metrics pertaining to release feedback.",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Stability Score",
   "type": "graph",
   "description": "Estimation of release stability based on feedback.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "release_score",
     "select": [
      [
       { "params": [ "score" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mail",
   "type": "graph",
   "description": "Mailing list references to releases.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "release_mail",
     "select": [
      [
       { "params": [ "reference_count" ], "type": "field" },
       { "params": [ "reference count" ], "type": "alias" }
      ],
      [
       { "params": [ "thread_count" ], "type": "field" },
       { "params": [ "thread count" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bug",
   "type": "graph",
   "description": "Number of bugs filed after a release.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "release_bug",
     "select": [
      [
       { "params": [ "bug_count" ], "type": "field" },
       { "params": [ "bug count" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Binary",
   "type": "graph",
   "description": "Total count of binaries and the number changed in a release.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "release_snapshot",
     "select": [
      [
       { "params": [ "binary_count" ], "type": "field" },
       { "params": [ "binary count" ], "type": "alias" }
      ],
      [
       { "params": [ "binary_unique_count" ], "type": "field" },
       { "params": [ "binary unique count" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}