{
 "title": "OSRT: Review",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Request - Priority",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "priority",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Review - opensuse-review-team",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "by_group", "operator": "=", "value": "opensuse-review-team" }
     ]
    }
   ]
  },
  {
   "title": "Review - leap-reviewers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "by_group", "operator": "=", "value": "leap-reviewers" }
     ]
    }
   ]
  },
  {
   "title": "Review - legal-auto",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "by_group", "operator": "=", "value": "legal-auto" }
     ]
    }
   ]
  },
  {
   "title": "Review - leaper",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "by_user", "operator": "=", "value": "leaper" }
     ]
    }
   ]
  },
  {
   "title": "Review - [factory-]repo-checker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "$tag_by_user.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "by_user" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "open_for" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "by_user", "operator": "=", "value": "repo-checker" },
      { "condition": "OR", "key": "by_user", "operator": "=", "value": "factory-repo-checker" }
     ]
    }
   ]
  },
  {
   "title": "Reviews - totals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_by_group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "by_group" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "review_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "group" },
      { "condition": "AND", "key": "by_group", "operator": "!=", "value": "factory-staging" }
     ]
    },
    {
     "alias": "$tag_by_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "by_user" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "review_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "by_user", "operator": "=", "value": "leaper" },
      { "condition": "OR", "key": "by_user", "operator": "=", "value": "repo-checker" }
     ]
    }
   ]
  },
  {
   "title": "Reviews - percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_by_group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "by_group" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "review_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "group" },
      { "condition": "AND", "key": "by_group", "operator": "!=", "value": "factory-staging" }
     ]
    },
    {
     "alias": "$tag_by_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "by_user" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "review_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "by_user", "operator": "=", "value": "leaper" },
      { "condition": "OR", "key": "by_user", "operator": "=", "value": "repo-checker" }
     ]
    }
   ]
  },
  {
   "title": "leaper - state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "by_user", "operator": "=", "value": "leaper" }
     ]
    }
   ]
  },
  {
   "title": "by_project",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "by_project" ], "type": "tag" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "project" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "project_package" }
     ]
    }
   ]
  },
  {
   "title": "by_project",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "by_project" ], "type": "tag" },
      { "params": [ "by_package" ], "type": "tag" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "project_package" }
     ]
    }
   ]
  },
  {
   "title": "leap-reviewers - who",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_who_completed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "who_completed" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "by_group", "operator": "=", "value": "leap-reviewers" }
     ]
    }
   ]
  },
  {
   "title": "leap-reviewers - who",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_who_completed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "who_completed" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "by_group", "operator": "=", "value": "leap-reviewers" }
     ]
    }
   ]
  },
  {
   "title": "opensuse-review-team - who",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_who_completed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "who_completed" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "by_group", "operator": "=", "value": "opensuse-review-team" }
     ]
    }
   ]
  },
  {
   "title": "opensuse-review-team - who",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_who_completed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "who_completed" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "review",
     "select": [
      [
       { "params": [ "open_for" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "by_group", "operator": "=", "value": "opensuse-review-team" }
     ]
    }
   ]
  }
 ]
}