format_version: 3
pipelines:
  SLES16.0.Images:
    group: SLES
    lock_behavior: unlockWhenFinished
    materials:
      repos:
        git: git://botmaster.suse.de/suse-repos.git
        auto_update: true
        whitelist:
          - SUSE:SLFO:Products:SLES:16.0_-_images.yaml
        destination: repos
      scripts:
        auto_update: true
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        whitelist:
          - DO_NOT_TRIGGER
        destination: scripts
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Expect.Images.To.Finish:
        resources:
        - staging-bot
        tasks:
        - script: |
            export PYTHONPATH=scripts
            ./scripts/gocd/verify-repo-built-successful.py -A https://api.suse.de -p SUSE:SLFO:Products:SLES:16.0 -r images

    - Release.Images.To.Test:
        approval: manual
        roles:
        - SLE
        environment_variables:
          OSC_CONFIG: /home/go/config/oscrc-totest-manager
        resources:
        - staging-bot
        tasks:
        - script: |-
            set -e
            for image in agama-installer-SLES kiwi-templates-Minimal; do
              osc -A https://api.suse.de release --target-project=SUSE:SLFO:Products:SLES:16.0:TEST --target-repository=images -r images SUSE:SLFO:Products:SLES:16.0 $image
            done
            osc -A https://api.suse.de release  --target-project=SUSE:SLFO:Products:SLES:16.0:TEST --target-repository=product -r product SUSE:SLFO:Products:SLES:16.0 000productcompose
            sleep 600
            while (osc -A https://api.suse.de/ api "/build/SUSE:SLFO:Products:SLES:16.0:TEST/_result?view=summary&repository=product" | grep "result project" | grep -v 'code="published" state="published">'); do
                echo PENDING
                sleep 600
            done
            osc -A https://api.suse.de/ api "/build/SUSE:SLFO:Products:SLES:16.0:TEST/_result?view=summary&repository=product" | grep "result project" | grep 'code="published" state="published">' && echo PUBLISHED
            while (osc -A https://api.suse.de/ api "/build/SUSE:SLFO:Products:SLES:16.0:TEST/_result?view=summary&repository=images" | grep "result project" | grep -v 'code="published" state="published">'); do
                echo PENDING
                sleep 600
            done
            osc -A https://api.suse.de/ api "/build/SUSE:SLFO:Products:SLES:16.0:TEST/_result?view=summary&repository=images" | grep "result project" | grep 'code="published" state="published">' && echo PUBLISHED

  SLES16.0.Images.To.Publish:
    group: SLES
    materials:
      repos:
        git: git://botmaster.suse.de/suse-repos.git
        auto_update: true
        whitelist:
          - SUSE:SLFO:Products:SLES:16.0_-_images.yaml
        destination: repos
      scripts:
        auto_update: true
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        whitelist:
          - DO_NOT_TRIGGER
        destination: scripts
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Release.Images:
        approval: manual
        roles:
        - SLE
        environment_variables:
          OSC_CONFIG: /home/go/config/oscrc-totest-manager
        resources:
        - staging-bot
        tasks:
        - script: |-
            set -e
            for image in agama-installer-SLES kiwi-templates-Minimal; do
              osc -A https://api.suse.de release --target-project=SUSE:SLFO:Products:SLES:16.0:PUBLISH --target-repository=images -r images SUSE:SLFO:Products:SLES:16.0:TEST $image
            done
            osc -A https://api.suse.de release  --target-project=SUSE:SLFO:Products:SLES:16.0:PUBLISH --target-repository=product -r product SUSE:SLFO:Products:SLES:16.0:TEST 000productcompose
            sleep 600
            while (osc -A https://api.suse.de/ api "/build/SUSE:SLFO:Products:SLES:16.0:PUBLISH/_result?view=summary&repository=product" | grep "result project" | grep -v 'code="published" state="published">'); do
                echo PENDING
                sleep 600
            done
            osc -A https://api.suse.de/ api "/build/SUSE:SLFO:Products:SLES:16.0:PUBLISH/_result?view=summary&repository=product" | grep "result project" | grep 'code="published" state="published">' && echo PUBLISHED
            while (osc -A https://api.suse.de/ api "/build/SUSE:SLFO:Products:SLES:16.0:PUBLISH/_result?view=summary&repository=images" | grep "result project" | grep -v 'code="published" state="published">'); do
                echo PENDING
                sleep 600
            done
            osc -A https://api.suse.de/ api "/build/SUSE:SLFO:Products:SLES:16.0:PUBLISH/_result?view=summary&repository=images" | grep "result project" | grep 'code="published" state="published">' && echo PUBLISHED
