format_version: 3
pipelines:
  SLE15.SP7.QU.Images.To.Test:
    group: SLE15.Target
    lock_behavior: unlockWhenFinished
    materials:
      repos:
        git: git://botmaster.suse.de/suse-repos.git
        auto_update: true
        whitelist:
          - SUSE:SLE-15-SP7:Update:QR_-_images.yaml
        destination: repos
      scripts:
        auto_update: true
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        whitelist:
          - DO_NOT_TRIGGER
        destination: scripts
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Expect.Images.To.Finish:
        resources:
        - staging-bot
        tasks:
        - script: |
            export PYTHONPATH=scripts
            set -e
            ./scripts/gocd/verify-repo-built-successful.py -A https://api.suse.de -p SUSE:SLE-15-SP7:Update:QR -r images

    - Release.Images:
        approval: manual
        roles:
        - SLE
        environment_variables:
          OSC_CONFIG: /home/go/config/oscrc-totest-manager
        resources:
        - staging-bot
        tasks:
        - script: |-
            set -e
            for product in kiwi-templates-Minimal kiwi-templates-Minimal-s390x 000product; do
              osc -A https://api.suse.de release SUSE:SLE-15-SP7:Update:QR $product
            done
            sleep 600
            while (osc -A https://api.suse.de/ api "/build/SUSE:SLE-15-SP7:Update:QR:TEST/_result?view=summary&repository=images" | grep "result project" | grep -v 'code="published" state="published">'); do
                echo PENDING
                sleep 600
            done
            osc -A https://api.suse.de/ api "/build/SUSE:SLE-15-SP7:Update:QR:TEST/_result?view=summary&repository=images" | grep "result project" | grep 'code="published" state="published">' && echo PUBLISHED

  SLE15.SP7.QU.Images.To.Publish:
    group: SLE15.Target
    materials:
      repos:
        git: git://botmaster.suse.de/suse-repos.git
        auto_update: true
        whitelist:
          - SUSE:SLE-15-SP7:Update:QR_-_images.yaml
        destination: repos
      scripts:
        auto_update: true
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        whitelist:
          - DO_NOT_TRIGGER
        destination: scripts
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Release.Images:
        approval: manual
        roles:
        - SLE
        environment_variables:
          OSC_CONFIG: /home/go/config/oscrc-totest-manager
        resources:
        - staging-bot
        tasks:
        - script: |-
            set -e
            osc -A https://api.suse.de release SUSE:SLE-15-SP7:Update:QR:TEST
            sleep 600
            while (osc -A https://api.suse.de/ api "/build/SUSE:SLE-15-SP7:Update:QR:PUBLISH/_result?view=summary&repository=images" | grep "result project" | grep -v 'code="published" state="published">'); do
                echo PENDING
                sleep 600
            done
            osc -A https://api.suse.de/ api "/build/SUSE:SLE-15-SP7:Update:QR:PUBLISH/_result?view=summary&repository=images" | grep "result project" | grep 'code="published" state="published">' && echo PUBLISHED

