format_version: 3
pipelines:
  TTM.Factory:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory
  TTM.Factory_ARM:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:ARM
  TTM.Factory_PowerPC:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:PowerPC
  TTM.Factory_WSL:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:WSL
  TTM.Factory_zSystems:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:zSystems
  TTM.Leap_15.1_ARM_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.1:ARM:Images
  TTM.Leap_15.1_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.1:Images
  TTM.Leap_15.2_ARM_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.2:ARM:Images
  TTM.Leap_15.2_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.2:Images
  TTM.Leap_15.2_MicroOS:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.2:MicroOS
  TTM.Leap_15.2_WSL:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.2:WSL
  TTM.Leap_15.3:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.3
  TTM.Jump_15.2_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Jump:15.2:Images
