format_version: 3
pipelines:
  TTM.Factory:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory
  TTM.Factory_ARM:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:ARM
  TTM.Factory_LegacyX86:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:LegacyX86
  TTM.Factory_PowerPC:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:PowerPC
  TTM.Factory_RISCV:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:RISCV
  TTM.Factory_zSystems:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Factory:zSystems
  TTM.Leap_15.6_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.6:Images
  TTM.Leap_15.6_ARM_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.6:ARM:Images
  TTM.Leap_16.0:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:16.0
  TTM.Leap_Micro_6.0:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:Micro:6.0
  TTM.Leap_Micro_6.0_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:Micro:6.0:Images
  TTM.Leap_Micro_6.1:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:Micro:6.1
  TTM.Leap_Micro_6.2:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:Micro:6.2
