format_version: 3
pipelines:
  openSUSE.Vagrant.Publish:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      ATLAS_TOKEN: '{{SECRET:[opensuse.secrets][ATLAS_TOKEN]}}'
    materials:
      git:
        git: https://github.com/openSUSE/opensuse-release-tools.git
    timer:
      spec: 0 0 0 ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        jobs:
          publish_Tumbleweed_x86_64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/tumbleweed/appliances/boxes/Tumbleweed.x86_64.json --organization opensuse --new-box-name Tumbleweed.x86_64
          publish_Tumbleweed_aarch64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/boxes/Tumbleweed.aarch64-libvirt_aarch64.json --organization opensuse --new-box-name Tumbleweed.aarch64
          publish_MicroOS_x86_64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64-Vagrant.json --organization opensuse --new-box-name MicroOS.x86_64
          publish_Kubic_x86_64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64-Kubic-kubeadm-Vagrant.json --organization opensuse --new-box-name Kubic.x86_64
          publish_MicroOS-ContainerHost_x86_64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64-ContainerHost-Vagrant.json --organization opensuse --new-box-name MicroOS-ContainerHost.x86_64
          publish_MicroOS_aarch64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/boxes/openSUSE-MicroOS.aarch64-Vagrant.json --organization opensuse --new-box-name MicroOS.aarch64
          publish_Kubic_aarch64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/boxes/openSUSE-MicroOS.aarch64-Kubic-kubeadm-Vagrant.json --organization opensuse --new-box-name Kubic.aarch64
          publish_MicroOS-ContainerHost_aarch64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/boxes/openSUSE-MicroOS.aarch64-ContainerHost-Vagrant.json --organization opensuse --new-box-name MicroOS-ContainerHost.aarch64
          publish_Leap-15_3_x86_64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/distribution/leap/15.3/appliances/boxes/Leap-15.3.x86_64.json --organization opensuse --new-box-name Leap-15.3.x86_64
          publish_Leap-15_3_aarch64:
            resources:
            - staging-bot
            tasks:
              - script: |
                  ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/distribution/leap/15.3/appliances/boxes/Leap-15.3.aarch64-libvirt_aarch64.json --organization opensuse --new-box-name Leap-15.3.aarch64